# databasedotcom.yml
client_id: 3MVG9rFJvQRVOvk45KQc_0XD_aUdAvY_zbWN5q3xL5a0M9XE8seAB9xAFng_eMz6.vxQrYjBicYxBFWGbgoJ_
client_secret: 8782750134572536306 
username: qjavaswing2009@gmail.com
password: passw0rdc6aeaRCziXIHbNqTrgtR0QKGX

